# Generated by Django 5.2.7 on 2025-11-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_monthly_overage',
            field=models.IntegerField(blank=True, help_text='Maximum overage addresses per month.', null=True),
        ),
    ]
