# Generated by Django 5.2.7 on 2025-11-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_company_max_monthly_overage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('pro', 'Pro'), ('corporate', 'Corporate')], max_length=20, null=True),
        ),
    ]
