# Generated by Django 5.2.7 on 2025-11-14 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_company_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('n_addresses', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.company')),
            ],
        ),
    ]
