# Generated by Django 5.2.7 on 2025-11-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_companyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(blank=True, help_text='Public support Company ID', null=True, unique=True),
        ),
    ]
