# Generated by Django 5.2.7 on 2025-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_companyinvite_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvite',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
