# Generated by Django 5.2.7 on 2025-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0012_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Email Verification'), ('reset', 'Password Reset')], default='verify', max_length=16),
        ),
    ]
